import { useCallback } from 'react'
import { useI18n } from '../i18n/I18nProvider'
import { getNested, interpolate } from '../i18n/locales'

/* Admin-only copy, kept apart from the public dictionaries so the public bundle stays unchanged. */

const fr = {
  meta: { title: 'US Bonds — Administration' },
  brand: 'Centre de contrôle',
  login: {
    kicker: 'Espace privé',
    title: 'Centre de contrôle US Bonds',
    lead: 'Accès réservé à l’administration. Gérez les demandes d’investissement et les souscriptions en temps réel.',
    password: 'Mot de passe administrateur',
    show: 'Afficher le mot de passe',
    hide: 'Masquer le mot de passe',
    submit: 'Se connecter',
    checking: 'Vérification…',
    back: 'Retour au site',
    secure: 'Session protégée · déconnexion automatique après 12 h',
    forgot: 'Mot de passe oublié ?',
    errors: {
      invalid: 'Mot de passe incorrect.',
      rate: 'Trop de tentatives. Réessayez dans 15 minutes.',
      server: 'Connexion impossible pour le moment.',
    },
    setup: {
      title: 'Accès non configuré',
      text: 'Définissez ADMIN_PASSWORD (12 caractères minimum) dans server/.env, puis redémarrez le serveur API. Il sera enregistré sous forme hachée.',
    },
  },
  forgot: {
    kicker: 'Réinitialisation',
    title: 'Mot de passe oublié',
    lead: 'Recevez un lien sécurisé pour définir un nouveau mot de passe. Il expire au bout de 30 minutes et ne fonctionne qu’une seule fois.',
    submit: 'Envoyer le lien',
    sending: 'Envoi…',
    back: 'Retour à la connexion',
    sentTitle: 'Lien envoyé',
    sentEmail: 'Un lien de réinitialisation a été envoyé à l’adresse e-mail de l’administrateur. Il est valable {{minutes}} minutes.',
    sentConsole:
      'Aucun service e-mail n’est configuré : le lien de réinitialisation a été affiché dans le terminal du serveur API. Il est valable {{minutes}} minutes.',
    resend: 'Renvoyer un lien',
    errors: {
      rate: 'Trop de demandes. Réessayez dans 15 minutes.',
      server: 'Envoi impossible pour le moment.',
    },
  },
  reset: {
    kicker: 'Sécurité',
    title: 'Nouveau mot de passe',
    lead: 'Choisissez un mot de passe long et unique. Toutes les sessions ouvertes seront déconnectées.',
    checking: 'Vérification du lien…',
    password: 'Nouveau mot de passe',
    confirm: 'Confirmer le mot de passe',
    submit: 'Enregistrer le mot de passe',
    saving: 'Enregistrement…',
    expires: 'Lien valable jusqu’à {{time}}',
    rules: {
      length: '12 caractères minimum',
      mix: 'Au moins 3 types : minuscules, majuscules, chiffres, symboles',
      match: 'Les deux saisies sont identiques',
    },
    strength: { label: 'Robustesse', 0: 'Trop faible', 1: 'Faible', 2: 'Moyenne', 3: 'Bonne', 4: 'Excellente' },
    errors: {
      short: '12 caractères minimum.',
      long: '128 caractères maximum.',
      weak: 'Mot de passe trop simple : mélangez au moins 3 types de caractères.',
      reused: 'Choisissez un mot de passe différent de l’actuel.',
      mismatch: 'Les mots de passe ne correspondent pas.',
      rate: 'Trop de tentatives. Réessayez dans 15 minutes.',
      server: 'Enregistrement impossible pour le moment.',
    },
    invalidTitle: 'Lien invalide',
    invalid: 'Ce lien de réinitialisation n’est pas valide ou a déjà été utilisé.',
    expiredTitle: 'Lien expiré',
    expired: 'Ce lien de réinitialisation a expiré. Demandez-en un nouveau.',
    request: 'Demander un nouveau lien',
    doneTitle: 'Mot de passe mis à jour',
    done: 'Votre nouveau mot de passe est enregistré de façon sécurisée. Toutes les sessions ont été déconnectées.',
    signIn: 'Se connecter',
  },
  nav: {
    primary: 'Navigation administration',
    overview: 'Vue d’ensemble',
    applications: 'Demandes',
    notifications: 'Notifications',
    site: 'Voir le site public',
    logout: 'Déconnexion',
    open: 'Ouvrir le menu',
    close: 'Fermer le menu',
    language: 'Langue',
  },
  live: { on: 'Temps réel', off: 'Reconnexion…' },
  statuses: {
    pending: 'En attente',
    approved: 'Approuvée',
    rejected: 'Refusée',
    active: 'Active',
    completed: 'Terminée',
  },
  actions: {
    approved: 'Approuver',
    rejected: 'Refuser',
    active: 'Activer la souscription',
    completed: 'Clôturer',
    pending: 'Remettre en attente',
  },
  overview: {
    kicker: 'Vue d’ensemble',
    title: 'Pilotage des souscriptions',
    lead: 'Chaque chiffre est calculé à l’instant depuis la base de données.',
    updated: 'Mis à jour à {{time}}',
    kpi: {
      total: 'Demandes totales',
      pending: 'En attente',
      active: 'Souscriptions actives',
      completed: 'Souscriptions terminées',
      requested: '{{amount}} demandés',
      today: '{{n}} aujourd’hui',
      share: '{{pct}} du total',
    },
    chart: {
      title: 'Demandes reçues',
      period: '30 derniers jours',
      tooltip: '{{n}} demande(s) · {{amount}}',
      empty: 'Aucune demande sur les 30 derniers jours.',
      axis: 'Nombre de demandes par jour',
    },
    distribution: 'Répartition par statut',
    capital: 'Capital demandé',
    offers: 'Par offre',
    durations: 'Par durée',
    recent: 'Dernières demandes',
    viewAll: 'Toutes les demandes',
    empty: 'Aucune demande reçue pour le moment. Les nouvelles inscriptions apparaîtront ici en temps réel.',
  },
  table: {
    kicker: 'Demandes',
    title: 'Demandes d’investissement',
    lead: 'Recherchez, filtrez et traitez chaque demande reçue via le formulaire.',
    search: 'Rechercher un nom, une ville, un e-mail…',
    clear: 'Effacer la recherche',
    all: 'Toutes',
    allOffers: 'Toutes les offres',
    allDurations: 'Toutes les durées',
    reset: 'Réinitialiser les filtres',
    results: '{{n}} résultat(s)',
    applicant: 'Demandeur',
    city: 'Ville',
    amount: 'Montant',
    duration: 'Durée',
    offer: 'Offre',
    date: 'Reçue le',
    status: 'Statut',
    actions: 'Actions',
    open: 'Ouvrir le dossier',
    sortBy: 'Trier par {{column}}',
    empty: 'Aucune demande ne correspond à ces critères.',
    none: 'Aucune demande reçue pour le moment.',
    page: 'Page {{page}} sur {{pages}}',
    prev: 'Page précédente',
    next: 'Page suivante',
    perPage: 'Lignes par page',
    statusFilter: 'Filtrer par statut',
  },
  detail: {
    kicker: 'Dossier',
    close: 'Fermer le dossier',
    identity: 'Identité',
    investment: 'Investissement',
    firstName: 'Prénom',
    lastName: 'Nom',
    city: 'Ville',
    email: 'E-mail',
    amount: 'Montant',
    duration: 'Durée',
    offer: 'Offre',
    submitted: 'Soumise le',
    locale: 'Langue du formulaire',
    reference: 'Référence',
    timeline: 'Historique',
    received: 'Demande reçue',
    noEmail: 'Non renseigné',
    phone: 'WhatsApp',
    copy: 'Copier l’e-mail',
    copied: 'Copié',
    write: 'Écrire',
    decision: 'Décision',
    noActions: 'Aucune action disponible pour ce statut.',
    updating: 'Mise à jour…',
    error: 'La mise à jour a échoué. Réessayez.',
    conflict: 'Ce changement de statut n’est pas autorisé.',
    notFound: 'Cette demande est introuvable.',
    languages: { fr: 'Français', en: 'English', ar: 'العربية' },
  },
  whatsapp: {
    title: 'Confirmation WhatsApp',
    to: 'Destinataire',
    message: 'Message de confirmation',
    language: 'Rédigé en {{language}}, la langue du formulaire.',
    send: 'Envoyer sur WhatsApp',
    copy: 'Copier le message',
    copied: 'Message copié',
    restore: 'Rétablir le message',
    opened: 'WhatsApp s’est ouvert avec le message de confirmation : il ne reste qu’à appuyer sur Envoyer.',
    blocked: 'Si WhatsApp ne s’est pas ouvert automatiquement, cliquez sur « Envoyer sur WhatsApp ».',
    noPhone: 'Aucun numéro WhatsApp n’a été fourni pour cette demande (envoyée avant l’ajout du champ).',
  },
  notifications: {
    title: 'Notifications',
    all: 'Toutes',
    unread: 'Non lues',
    markAll: 'Tout marquer comme lu',
    empty: 'Aucune notification pour le moment.',
    emptyUnread: 'Vous êtes à jour.',
    newApplication: 'Nouvelle demande reçue',
    open: 'Ouvrir la demande',
    markRead: 'Marquer comme lue',
    markUnread: 'Marquer comme non lue',
    bell: 'Notifications ({{n}} non lues)',
    close: 'Fermer les notifications',
  },
  toast: { open: 'Voir la demande', dismiss: 'Ignorer' },
  errors: {
    load: 'Chargement impossible.',
    db: 'Base de données indisponible.',
    retry: 'Réessayer',
  },
  justNow: 'à l’instant',
}

const en = {
  meta: { title: 'US Bonds — Administration' },
  brand: 'Control center',
  login: {
    kicker: 'Private area',
    title: 'US Bonds control center',
    lead: 'Restricted to the administration. Manage investment applications and subscriptions in real time.',
    password: 'Admin password',
    show: 'Show password',
    hide: 'Hide password',
    submit: 'Sign in',
    checking: 'Checking…',
    back: 'Back to the website',
    secure: 'Protected session · signs out automatically after 12 h',
    forgot: 'Forgot password?',
    errors: {
      invalid: 'Incorrect password.',
      rate: 'Too many attempts. Try again in 15 minutes.',
      server: 'Unable to sign in right now.',
    },
    setup: {
      title: 'Access not configured',
      text: 'Set ADMIN_PASSWORD (12 characters minimum) in server/.env, then restart the API server. It will be stored hashed.',
    },
  },
  forgot: {
    kicker: 'Reset',
    title: 'Forgot password',
    lead: 'Receive a secure link to set a new password. It expires after 30 minutes and works only once.',
    submit: 'Send the link',
    sending: 'Sending…',
    back: 'Back to sign in',
    sentTitle: 'Link sent',
    sentEmail: 'A reset link was sent to the administrator email address. It is valid for {{minutes}} minutes.',
    sentConsole: 'No email service is configured: the reset link was printed in the API server terminal. It is valid for {{minutes}} minutes.',
    resend: 'Send another link',
    errors: {
      rate: 'Too many requests. Try again in 15 minutes.',
      server: 'Unable to send right now.',
    },
  },
  reset: {
    kicker: 'Security',
    title: 'New password',
    lead: 'Choose a long, unique password. Every open session will be signed out.',
    checking: 'Checking the link…',
    password: 'New password',
    confirm: 'Confirm password',
    submit: 'Save password',
    saving: 'Saving…',
    expires: 'Link valid until {{time}}',
    rules: {
      length: '12 characters minimum',
      mix: 'At least 3 types: lowercase, uppercase, digits, symbols',
      match: 'Both entries match',
    },
    strength: { label: 'Strength', 0: 'Too weak', 1: 'Weak', 2: 'Fair', 3: 'Good', 4: 'Excellent' },
    errors: {
      short: '12 characters minimum.',
      long: '128 characters maximum.',
      weak: 'Password too simple: mix at least 3 types of characters.',
      reused: 'Choose a password different from the current one.',
      mismatch: 'The passwords do not match.',
      rate: 'Too many attempts. Try again in 15 minutes.',
      server: 'Unable to save right now.',
    },
    invalidTitle: 'Invalid link',
    invalid: 'This reset link is not valid or has already been used.',
    expiredTitle: 'Link expired',
    expired: 'This reset link has expired. Request a new one.',
    request: 'Request a new link',
    doneTitle: 'Password updated',
    done: 'Your new password is stored securely. Every session has been signed out.',
    signIn: 'Sign in',
  },
  nav: {
    primary: 'Admin navigation',
    overview: 'Overview',
    applications: 'Applications',
    notifications: 'Notifications',
    site: 'View public site',
    logout: 'Sign out',
    open: 'Open menu',
    close: 'Close menu',
    language: 'Language',
  },
  live: { on: 'Real time', off: 'Reconnecting…' },
  statuses: {
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    active: 'Active',
    completed: 'Completed',
  },
  actions: {
    approved: 'Approve',
    rejected: 'Reject',
    active: 'Activate subscription',
    completed: 'Mark completed',
    pending: 'Move back to pending',
  },
  overview: {
    kicker: 'Overview',
    title: 'Subscription control',
    lead: 'Every figure is computed live from the database.',
    updated: 'Updated at {{time}}',
    kpi: {
      total: 'Total applications',
      pending: 'Pending',
      active: 'Active subscriptions',
      completed: 'Completed subscriptions',
      requested: '{{amount}} requested',
      today: '{{n}} today',
      share: '{{pct}} of total',
    },
    chart: {
      title: 'Applications received',
      period: 'Last 30 days',
      tooltip: '{{n}} application(s) · {{amount}}',
      empty: 'No applications in the last 30 days.',
      axis: 'Applications per day',
    },
    distribution: 'Status breakdown',
    capital: 'Requested capital',
    offers: 'By offer',
    durations: 'By duration',
    recent: 'Latest applications',
    viewAll: 'All applications',
    empty: 'No applications yet. New registrations will appear here in real time.',
  },
  table: {
    kicker: 'Applications',
    title: 'Investment applications',
    lead: 'Search, filter and process every application received through the form.',
    search: 'Search a name, city, email…',
    clear: 'Clear search',
    all: 'All',
    allOffers: 'All offers',
    allDurations: 'All durations',
    reset: 'Reset filters',
    results: '{{n}} result(s)',
    applicant: 'Applicant',
    city: 'City',
    amount: 'Amount',
    duration: 'Duration',
    offer: 'Offer',
    date: 'Received',
    status: 'Status',
    actions: 'Actions',
    open: 'Open file',
    sortBy: 'Sort by {{column}}',
    empty: 'No application matches these criteria.',
    none: 'No applications received yet.',
    page: 'Page {{page}} of {{pages}}',
    prev: 'Previous page',
    next: 'Next page',
    perPage: 'Rows per page',
    statusFilter: 'Filter by status',
  },
  detail: {
    kicker: 'File',
    close: 'Close file',
    identity: 'Identity',
    investment: 'Investment',
    firstName: 'First name',
    lastName: 'Last name',
    city: 'City',
    email: 'Email',
    amount: 'Amount',
    duration: 'Duration',
    offer: 'Offer',
    submitted: 'Submitted on',
    locale: 'Form language',
    reference: 'Reference',
    timeline: 'History',
    received: 'Application received',
    noEmail: 'Not provided',
    phone: 'WhatsApp',
    copy: 'Copy email',
    copied: 'Copied',
    write: 'Write',
    decision: 'Decision',
    noActions: 'No action available for this status.',
    updating: 'Updating…',
    error: 'The update failed. Please try again.',
    conflict: 'This status change is not allowed.',
    notFound: 'This application could not be found.',
    languages: { fr: 'Français', en: 'English', ar: 'العربية' },
  },
  whatsapp: {
    title: 'WhatsApp confirmation',
    to: 'Recipient',
    message: 'Confirmation message',
    language: 'Written in {{language}}, the language of the form.',
    send: 'Send on WhatsApp',
    copy: 'Copy message',
    copied: 'Message copied',
    restore: 'Restore message',
    opened: 'WhatsApp opened with the confirmation message: just press Send.',
    blocked: 'If WhatsApp did not open automatically, click “Send on WhatsApp”.',
    noPhone: 'No WhatsApp number was provided for this application (sent before the field existed).',
  },
  notifications: {
    title: 'Notifications',
    all: 'All',
    unread: 'Unread',
    markAll: 'Mark all as read',
    empty: 'No notifications yet.',
    emptyUnread: 'You are all caught up.',
    newApplication: 'New application received',
    open: 'Open application',
    markRead: 'Mark as read',
    markUnread: 'Mark as unread',
    bell: 'Notifications ({{n}} unread)',
    close: 'Close notifications',
  },
  toast: { open: 'View application', dismiss: 'Dismiss' },
  errors: {
    load: 'Unable to load.',
    db: 'Database unavailable.',
    retry: 'Retry',
  },
  justNow: 'just now',
}

const ar = {
  meta: { title: 'US Bonds — لوحة الإدارة' },
  brand: 'مركز التحكم',
  login: {
    kicker: 'مساحة خاصة',
    title: 'مركز التحكم US Bonds',
    lead: 'الدخول مخصص للإدارة فقط. أدِر طلبات الاستثمار والاشتراكات في الوقت الفعلي.',
    password: 'كلمة مرور المسؤول',
    show: 'إظهار كلمة المرور',
    hide: 'إخفاء كلمة المرور',
    submit: 'تسجيل الدخول',
    checking: 'جارٍ التحقق…',
    back: 'العودة إلى الموقع',
    secure: 'جلسة محمية · تسجيل خروج تلقائي بعد 12 ساعة',
    forgot: 'نسيت كلمة المرور؟',
    errors: {
      invalid: 'كلمة المرور غير صحيحة.',
      rate: 'محاولات كثيرة جداً. حاول مجدداً بعد 15 دقيقة.',
      server: 'تعذّر تسجيل الدخول حالياً.',
    },
    setup: {
      title: 'الدخول غير مُهيّأ',
      text: 'عرّف ADMIN_PASSWORD (12 حرفاً على الأقل) في server/.env ثم أعد تشغيل خادم الـAPI. سيتم حفظها بشكل مُجزّأ (hash).',
    },
  },
  forgot: {
    kicker: 'إعادة التعيين',
    title: 'نسيت كلمة المرور',
    lead: 'احصل على رابط آمن لتعيين كلمة مرور جديدة. تنتهي صلاحيته بعد 30 دقيقة ولا يعمل إلا مرة واحدة.',
    submit: 'إرسال الرابط',
    sending: 'جارٍ الإرسال…',
    back: 'العودة إلى تسجيل الدخول',
    sentTitle: 'تم إرسال الرابط',
    sentEmail: 'تم إرسال رابط إعادة التعيين إلى البريد الإلكتروني للمسؤول. صالح لمدة {{minutes}} دقيقة.',
    sentConsole: 'لا توجد خدمة بريد مُهيّأة: تم عرض رابط إعادة التعيين في نافذة أوامر خادم الـAPI. صالح لمدة {{minutes}} دقيقة.',
    resend: 'إرسال رابط آخر',
    errors: {
      rate: 'طلبات كثيرة جداً. حاول مجدداً بعد 15 دقيقة.',
      server: 'تعذّر الإرسال حالياً.',
    },
  },
  reset: {
    kicker: 'الأمان',
    title: 'كلمة مرور جديدة',
    lead: 'اختر كلمة مرور طويلة وفريدة. سيتم تسجيل الخروج من كل الجلسات المفتوحة.',
    checking: 'جارٍ التحقق من الرابط…',
    password: 'كلمة المرور الجديدة',
    confirm: 'تأكيد كلمة المرور',
    submit: 'حفظ كلمة المرور',
    saving: 'جارٍ الحفظ…',
    expires: 'الرابط صالح حتى {{time}}',
    rules: {
      length: '12 حرفاً على الأقل',
      mix: '3 أنواع على الأقل: أحرف صغيرة، كبيرة، أرقام، رموز',
      match: 'الإدخالان متطابقان',
    },
    strength: { label: 'القوة', 0: 'ضعيفة جداً', 1: 'ضعيفة', 2: 'متوسطة', 3: 'جيدة', 4: 'ممتازة' },
    errors: {
      short: '12 حرفاً على الأقل.',
      long: '128 حرفاً كحد أقصى.',
      weak: 'كلمة مرور بسيطة جداً: امزج 3 أنواع من الأحرف على الأقل.',
      reused: 'اختر كلمة مرور مختلفة عن الحالية.',
      mismatch: 'كلمتا المرور غير متطابقتين.',
      rate: 'محاولات كثيرة جداً. حاول مجدداً بعد 15 دقيقة.',
      server: 'تعذّر الحفظ حالياً.',
    },
    invalidTitle: 'رابط غير صالح',
    invalid: 'رابط إعادة التعيين هذا غير صالح أو تم استخدامه مسبقاً.',
    expiredTitle: 'انتهت صلاحية الرابط',
    expired: 'انتهت صلاحية رابط إعادة التعيين. اطلب رابطاً جديداً.',
    request: 'طلب رابط جديد',
    doneTitle: 'تم تحديث كلمة المرور',
    done: 'تم حفظ كلمة المرور الجديدة بشكل آمن. تم تسجيل الخروج من كل الجلسات.',
    signIn: 'تسجيل الدخول',
  },
  nav: {
    primary: 'تنقّل الإدارة',
    overview: 'نظرة عامة',
    applications: 'الطلبات',
    notifications: 'الإشعارات',
    site: 'عرض الموقع العام',
    logout: 'تسجيل الخروج',
    open: 'فتح القائمة',
    close: 'إغلاق القائمة',
    language: 'اللغة',
  },
  live: { on: 'مباشر', off: 'إعادة الاتصال…' },
  statuses: {
    pending: 'قيد الانتظار',
    approved: 'مقبول',
    rejected: 'مرفوض',
    active: 'نشط',
    completed: 'مكتمل',
  },
  actions: {
    approved: 'قبول',
    rejected: 'رفض',
    active: 'تفعيل الاشتراك',
    completed: 'إنهاء',
    pending: 'إعادة إلى الانتظار',
  },
  overview: {
    kicker: 'نظرة عامة',
    title: 'إدارة الاشتراكات',
    lead: 'كل رقم يُحتسب لحظياً من قاعدة البيانات.',
    updated: 'آخر تحديث {{time}}',
    kpi: {
      total: 'إجمالي الطلبات',
      pending: 'قيد الانتظار',
      active: 'اشتراكات نشطة',
      completed: 'اشتراكات مكتملة',
      requested: 'المبلغ المطلوب: {{amount}}',
      today: 'اليوم: {{n}}',
      share: '{{pct}} من الإجمالي',
    },
    chart: {
      title: 'الطلبات المستلمة',
      period: 'آخر 30 يوماً',
      tooltip: 'عدد الطلبات: {{n}} · {{amount}}',
      empty: 'لا توجد طلبات خلال آخر 30 يوماً.',
      axis: 'عدد الطلبات يومياً',
    },
    distribution: 'التوزيع حسب الحالة',
    capital: 'رأس المال المطلوب',
    offers: 'حسب العرض',
    durations: 'حسب المدة',
    recent: 'أحدث الطلبات',
    viewAll: 'كل الطلبات',
    empty: 'لا توجد طلبات بعد. ستظهر التسجيلات الجديدة هنا في الوقت الفعلي.',
  },
  table: {
    kicker: 'الطلبات',
    title: 'طلبات الاستثمار',
    lead: 'ابحث وصفِّ وعالج كل طلب مستلم عبر النموذج.',
    search: 'ابحث عن اسم أو مدينة أو بريد…',
    clear: 'مسح البحث',
    all: 'الكل',
    allOffers: 'كل العروض',
    allDurations: 'كل المدد',
    reset: 'إعادة ضبط المرشحات',
    results: 'النتائج: {{n}}',
    applicant: 'مقدّم الطلب',
    city: 'المدينة',
    amount: 'المبلغ',
    duration: 'المدة',
    offer: 'العرض',
    date: 'تاريخ الاستلام',
    status: 'الحالة',
    actions: 'إجراءات',
    open: 'فتح الملف',
    sortBy: 'ترتيب حسب {{column}}',
    empty: 'لا يوجد طلب يطابق هذه المعايير.',
    none: 'لم يتم استلام أي طلب بعد.',
    page: 'الصفحة {{page}} من {{pages}}',
    prev: 'الصفحة السابقة',
    next: 'الصفحة التالية',
    perPage: 'عدد الأسطر',
    statusFilter: 'تصفية حسب الحالة',
  },
  detail: {
    kicker: 'الملف',
    close: 'إغلاق الملف',
    identity: 'الهوية',
    investment: 'الاستثمار',
    firstName: 'الاسم',
    lastName: 'اللقب',
    city: 'المدينة',
    email: 'البريد الإلكتروني',
    amount: 'المبلغ',
    duration: 'المدة',
    offer: 'العرض',
    submitted: 'تاريخ الإرسال',
    locale: 'لغة النموذج',
    reference: 'المرجع',
    timeline: 'السجل',
    received: 'تم استلام الطلب',
    noEmail: 'غير متوفر',
    phone: 'واتساب',
    copy: 'نسخ البريد',
    copied: 'تم النسخ',
    write: 'مراسلة',
    decision: 'القرار',
    noActions: 'لا يوجد إجراء متاح لهذه الحالة.',
    updating: 'جارٍ التحديث…',
    error: 'فشل التحديث. حاول مجدداً.',
    conflict: 'هذا التغيير في الحالة غير مسموح.',
    notFound: 'تعذّر العثور على هذا الطلب.',
    languages: { fr: 'Français', en: 'English', ar: 'العربية' },
  },
  whatsapp: {
    title: 'تأكيد عبر واتساب',
    to: 'المستلم',
    message: 'رسالة التأكيد',
    language: 'مكتوبة بـ{{language}}، لغة النموذج.',
    send: 'إرسال عبر واتساب',
    copy: 'نسخ الرسالة',
    copied: 'تم نسخ الرسالة',
    restore: 'استعادة الرسالة',
    opened: 'تم فتح واتساب مع رسالة التأكيد: يكفي الضغط على إرسال.',
    blocked: 'إذا لم يُفتح واتساب تلقائياً، اضغط على «إرسال عبر واتساب».',
    noPhone: 'لم يتم تقديم رقم واتساب لهذا الطلب (أُرسل قبل إضافة الحقل).',
  },
  notifications: {
    title: 'الإشعارات',
    all: 'الكل',
    unread: 'غير المقروءة',
    markAll: 'تعليم الكل كمقروء',
    empty: 'لا توجد إشعارات بعد.',
    emptyUnread: 'لا جديد.',
    newApplication: 'تم استلام طلب جديد',
    open: 'فتح الطلب',
    markRead: 'تعليم كمقروء',
    markUnread: 'تعليم كغير مقروء',
    bell: 'الإشعارات (غير المقروءة: {{n}})',
    close: 'إغلاق الإشعارات',
  },
  toast: { open: 'عرض الطلب', dismiss: 'تجاهل' },
  errors: {
    load: 'تعذّر التحميل.',
    db: 'قاعدة البيانات غير متاحة.',
    retry: 'إعادة المحاولة',
  },
  justNow: 'الآن',
}

const dictionaries = { fr, en, ar }

/** `a(key, vars)` for admin copy; falls back to French, then to the key itself. */
export const useAdminText = () => {
  const { locale } = useI18n()
  return useCallback(
    (key, vars) => {
      const found = getNested(dictionaries[locale] || fr, key) ?? getNested(fr, key)
      if (typeof found !== 'string') return key
      return vars ? interpolate(found, vars) : found
    },
    [locale],
  )
}
