import Plan from '../models/Plan.js';
import { TRIAL_DAYS } from './licenseService.js';

/** Stable plan seeds for P4. Idempotent upsert by code. */
export const DEFAULT_PLANS = [
  {
    code: 'free_trial',
    name: 'Free Trial',
    description: 'Evaluation period with limited fleet size.',
    priceAmount: 0,
    currency: 'MAD',
    interval: 'month',
    trialDaysDefault: TRIAL_DAYS,
    isPublic: true,
    sortOrder: 10,
    features: {
      maxVehicles: 5,
      maxStaff: 1,
      maxBookingsPerMonth: 50,
      maxStorageMb: 500,
      customDomain: false,
      subdomain: true,
      whatsappSettings: true,
      promotions: false,
      contractsPdf: true,
      analytics: false,
      apiAccess: false,
      prioritySupport: false,
    },
  },
  {
    code: 'basic',
    name: 'Basic',
    description: 'For small agencies getting started.',
    priceAmount: 299,
    currency: 'MAD',
    interval: 'month',
    trialDaysDefault: 0,
    isPublic: true,
    sortOrder: 20,
    features: {
      maxVehicles: 15,
      maxStaff: 2,
      maxBookingsPerMonth: 200,
      maxStorageMb: 2048,
      customDomain: false,
      subdomain: true,
      whatsappSettings: true,
      promotions: true,
      contractsPdf: true,
      analytics: false,
      apiAccess: false,
      prioritySupport: false,
    },
  },
  {
    code: 'pro',
    name: 'Pro',
    description: 'Growing fleets with custom domain and analytics.',
    priceAmount: 599,
    currency: 'MAD',
    interval: 'month',
    trialDaysDefault: 0,
    isPublic: true,
    sortOrder: 30,
    features: {
      maxVehicles: 50,
      maxStaff: 5,
      maxBookingsPerMonth: 1000,
      maxStorageMb: 10240,
      customDomain: true,
      subdomain: true,
      whatsappSettings: true,
      promotions: true,
      contractsPdf: true,
      analytics: true,
      apiAccess: false,
      prioritySupport: true,
    },
  },
  {
    code: 'enterprise',
    name: 'Enterprise',
    description: 'Custom limits and priority support.',
    priceAmount: 0,
    currency: 'MAD',
    interval: 'month',
    trialDaysDefault: 0,
    isPublic: false,
    sortOrder: 40,
    features: {
      maxVehicles: null,
      maxStaff: null,
      maxBookingsPerMonth: null,
      maxStorageMb: null,
      customDomain: true,
      subdomain: true,
      whatsappSettings: true,
      promotions: true,
      contractsPdf: true,
      analytics: true,
      apiAccess: true,
      prioritySupport: true,
    },
  },
  {
    code: 'legacy_grandfathered',
    name: 'Legacy (grandfathered)',
    description: 'Existing agencies migrated with full access.',
    priceAmount: 0,
    currency: 'MAD',
    interval: 'month',
    trialDaysDefault: 0,
    isPublic: false,
    sortOrder: 5,
    features: {
      maxVehicles: null,
      maxStaff: null,
      maxBookingsPerMonth: null,
      maxStorageMb: null,
      customDomain: true,
      subdomain: true,
      whatsappSettings: true,
      promotions: true,
      contractsPdf: true,
      analytics: true,
      apiAccess: true,
      prioritySupport: true,
    },
  },
];

export const ensureDefaultPlans = async () => {
  for (const plan of DEFAULT_PLANS) {
    await Plan.findOneAndUpdate(
      { code: plan.code },
      { $set: { ...plan, active: true } },
      { upsert: true, new: true, setDefaultsOnInsert: true },
    );
  }
  return Plan.find({ active: true }).sort({ sortOrder: 1 }).lean();
};

export default { DEFAULT_PLANS, ensureDefaultPlans };
